/**
  ******************************************************************************
  * @file    Project/STM32F10x_StdPeriph_Template/stm32f10x_it.c 
  * @author  MCD Application Team
  * @version V3.4.0
  * @date    10/15/2010
  * @brief   Main Interrupt Service Routines.
  *          This file provides template for all exceptions handler and 
  *          peripherals interrupt service routine.
  ******************************************************************************
  * @copy
  *
  * THE PRESENT FIRMWARE WHICH IS FOR GUIDANCE ONLY AIMS AT PROVIDING CUSTOMERS
  * WITH CODING INFORMATION REGARDING THEIR PRODUCTS IN ORDER FOR THEM TO SAVE
  * TIME. AS A RESULT, STMICROELECTRONICS SHALL NOT BE HELD LIABLE FOR ANY
  * DIRECT, INDIRECT OR CONSEQUENTIAL DAMAGES WITH RESPECT TO ANY CLAIMS ARISING
  * FROM THE CONTENT OF SUCH FIRMWARE AND/OR THE USE MADE BY CUSTOMERS OF THE
  * CODING INFORMATION CONTAINED HEREIN IN CONNECTION WITH THEIR PRODUCTS.
  *
  * <h2><center>&copy; COPYRIGHT 2010 STMicroelectronics</center></h2>
  */ 

/* Includes ------------------------------------------------------------------*/
#include "stm32f10x_it.h"
#include "usb_istr.h"

#include "mod_radio_control.h"
#include "mod_signaling_led.h"
#include "mod_sensors.h"

/* Private define ------------------------------------------------------------*/
/* Private typedef -----------------------------------------------------------*/
/* Private macro -------------------------------------------------------------*/
/* Private variables ---------------------------------------------------------*/
volatile bool uart_data_sent     = false;
volatile bool distMeasReady      = false;
/* Private function prototypes -----------------------------------------------*/
/* Private functions ---------------------------------------------------------*/

/******************************************************************************/
/*            Cortex-M3 Processor Exceptions Handlers                         */
/******************************************************************************/

/**
  * @brief   This function handles NMI exception.
  * @param  None
  * @retval None
  */
void NMI_Handler(void)
{
}

/**
  * @brief  This function handles Hard Fault exception.
  * @param  None
  * @retval None
  */
void HardFault_Handler(void)
{
  /* Go to infinite loop when Hard Fault exception occurs */
  while (1)
  {
  }
}

/**
  * @brief  This function handles Memory Manage exception.
  * @param  None
  * @retval None
  */
void MemManage_Handler(void)
{
  /* Go to infinite loop when Memory Manage exception occurs */
  while (1)
  {
  }
}

/**
  * @brief  This function handles Bus Fault exception.
  * @param  None
  * @retval None
  */
void BusFault_Handler(void)
{
  /* Go to infinite loop when Bus Fault exception occurs */
  while (1)
  {
  }
}

/**
  * @brief  This function handles Usage Fault exception.
  * @param  None
  * @retval None
  */
void UsageFault_Handler(void)
{
  /* Go to infinite loop when Usage Fault exception occurs */
  while (1)
  {
  }
}

/**
  * @brief  This function handles Debug Monitor exception.
  * @param  None
  * @retval None
  */
void DebugMon_Handler(void)
{
}

/*******************************************************************************
* Function Name  : PendSV_Handler
* Description    : This function handles PendSVC exception.
* Input          : None
* Output         : None
* Return         : None
*******************************************************************************/
// declared in port.c FreeRTOS file
//void PendSV_Handler(void)
//{
//}

/*******************************************************************************
* Function Name  : SysTick_Handler
* Description    : This function handles SysTick Handler.
* Input          : None
* Output         : None
* Return         : None
*******************************************************************************/
// declared in port.c FreeRTOS file
//void SysTick_Handler(void)
//{
//}

/*******************************************************************************
* Function Name  : USB_IRQHandler
* Description    : This function handles USB Low Priority interrupts
*                  requests.
* Input          : None
* Output         : None
* Return         : None
*******************************************************************************/
void USB_LP_CAN1_RX0_IRQHandler(void)
{
    portBASE_TYPE xHigherPriorityTaskWoken = pdFALSE;

    USB_Istr();
    xSemaphoreGiveFromISR(xSemaphLedSignal, &xHigherPriorityTaskWoken);
    portEND_SWITCHING_ISR(xHigherPriorityTaskWoken);
}

/*******************************************************************************
* Function Name  : USART1_IRQHandler
* Description    : This function handles interrupt events generated by USART1
* Input          : None
* Output         : None
* Return         : None
*******************************************************************************/
#include <stdio.h>
void USART1_IRQHandler(void)
{

    static uint8_t frameCellPos = 0;
    
    if(USART_GetFlagStatus(USART1, USART_FLAG_TC) == SET) {
        USART_ClearFlag(USART1, USART_FLAG_TC);
        uart_data_sent = true;
    }

    if(USART_GetFlagStatus(USART1, USART_FLAG_RXNE) == SET) {
        uint16_t data = USART_ReceiveData(USART1);
        //USART_ClearFlag(USART1, USART_FLAG_RXNE);
        //printf("uart data: %d\n", data);

        if(data == RADIO_UART_MASTER_ADDRESS) {
            // ignore the first received byte (uart target address)
            // and reset frame byte position
            radioData.rxState = UART_FRAME_ST_RECEIVING;
            frameCellPos = 0;
        }
        else {
            radioData.frame.uartRxFrame.buffer[frameCellPos] = (uint8_t)data;
            frameCellPos++;

            radioData.rxState = UART_FRAME_ST_RECEIVING;
            if(radioData.frame.uartRxFrame.rxMsg.function == UART_FUNC_MSG_RECEIVE &&
                frameCellPos == RADIO_FRAME_SIZE)
            {
                portBASE_TYPE xHigherPriorityTaskWoken = pdFALSE;
                uint8_t i = 0;
                
                for(i=0; i<RADIO_FRAME_SIZE+1; i++) {
                    //printf("%d/%d ", i, frame[i]);
                }
                //printf("\r\n");
                
                if(is_radio_data_checksum_correct(&radioData) == true) {
                    radioData.radioRxMsgReady = radioData.frame.uartRxFrame.rxMsg;
                    xSemaphoreGiveFromISR(xSemaphRadioPacketReady, &xHigherPriorityTaskWoken);
                    portEND_SWITCHING_ISR(xHigherPriorityTaskWoken);
                }
                else {
                    printf("Radio data checksum incorrect, neglecing frame!\r\n");
                }
            }
            else if(radioData.frame.uartRxFrame.rxMsg.function == UART_FUNC_RESPONSE &&
                frameCellPos == RADIO_RESP_FRAME_SIZE)
            {
                radioData.radioRxRespReady = radioData.frame.uartRxFrame.rxResp;
                radioData.txState = UART_FRAME_ST_READY;
            }
            else {
                // not supported, do nothing
            }
        }
    }

}

/*******************************************************************************
* Function Name  : TIM1_CC_IRQHandler
* Description    : This function handles Capture Compare Events generated by
                   Timer1
* Input          : None
* Output         : None
* Return         : None
*******************************************************************************/
void TIM1_CC_IRQHandler(void) 
{
    if(TIM_GetITStatus(TIM1, TIM_IT_CC1) == SET) {
        TIM_ClearITPendingBit(TIM1, TIM_IT_CC1);
        TIM_SetCounter(TIM1, 0);

        // ADC is triggered by CC1 with 50ms intervals
        ADC_ExternalTrigConvCmd(ADC1, ENABLE);
    }

}

/*******************************************************************************
* Function Name  : TIM4_IRQHandler
* Description    : This function handles all events generated by Timer4                 
* Input          : None
* Output         : None
* Return         : None
*******************************************************************************/
void TIM4_IRQHandler(void)
{
    if(TIM_GetITStatus(TIM4, TIM_IT_Trigger) == SET)
    {
        uint16_t distanceInTime = TIM_GetCounter(TIM4);
        TIM_ClearITPendingBit(TIM4, TIM_IT_Trigger);

        if(sensorInUse == SENSOR_FRONT) {
            if(distanceInTime < 10U) {
                // filter out all events of duration less than 10us
                // which can be voltage iddles when sensor power is off
            }
            else {
                if(GPIO_ReadInputDataBit(GPIOB, GPIO_Pin_7) == Bit_RESET) {
                    distance[SENSOR_FRONT] = (340U*distanceInTime/2)*0.0001;
                    distMeasReady = true;
                }
                else {
                    // neglecting start of measurement on rising edge of the signal
                    // it may occur either on filtered out time or after it
                }
            }
        }
        if(sensorInUse == SENSOR_REAR) {
            if(GPIO_ReadInputDataBit(GPIOB, GPIO_Pin_6) == Bit_RESET)
            {
                distance[SENSOR_REAR] = (340U*(distanceInTime-200U)/2)*0.0001;
                distMeasReady = true;
            }
            else {
                // rising edge as measurement start not present in SDM-IO sensor
                // time counting since trigger, hence no action in here
            }
        }
    }

}

/*******************************************************************************
* Function Name  : PVD_IRQHandler
* Description    : This function handles events generated by ext. interrupt 
                   line 16 (internally connected to voltage detector)
* Input          : None
* Output         : None
* Return         : None
*******************************************************************************/
void PVD_IRQHandler(void)
{

    if(EXTI_GetITStatus(EXTI_Line16) == SET)
    {
        FlagStatus PVDO_state = RESET;
        EXTI_ClearITPendingBit(EXTI_Line16);

        PVDO_state = PWR_GetFlagStatus(PWR_FLAG_PVDO);
        vCheckSupplyVoltage(PVDO_state);
    }

}
/*******************************************************************************
* Function Name  : USB_FS_WKUP_IRQHandler
* Description    : This function handles USB WakeUp interrupt request.
* Input          : None
* Output         : None
* Return         : None
*******************************************************************************/

//#if defined(STM32L1XX_MD) || defined(STM32L1XX_HD)|| defined(STM32L1XX_MD_PLUS)
//void USB_FS_WKUP_IRQHandler(void)
//#else
//void USBWakeUp_IRQHandler(void)
//#endif
//{
//  EXTI_ClearITPendingBit(EXTI_Line18);
//}

/******************************************************************************/
/*                 STM32 Peripherals Interrupt Handlers                   */
/*  Add here the Interrupt Handler for the used peripheral(s) (PPP), for the  */
/*  available peripheral interrupt handler's name please refer to the startup */
/*  file (startup_stm32xxx.s).                                            */
/******************************************************************************/

/**
  * @brief  This function handles PPP interrupt request.
  * @param  None
  * @retval None
  */
/*void PPP_IRQHandler(void)
{
}*/

/**
  * @}
  */ 


/******************* (C) COPYRIGHT 2010 STMicroelectronics *****END OF FILE****/
